steps:
  # Build and Push Docker Image 1
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/<t-project-449309>/gke-repo/quickstart-image:v1', './app1']
    id: 'Build Docker Image 1'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/<t-project-449309>/gke-repo/quickstart-image:v1']
    id: 'Push Docker Image 1'

  # Build and Push Docker Image 2
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/<t-project-449309>/gke-repo/flask-image:v1', './app2']
    id: 'Build Docker Image 2'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/<t-project-449309>/gke-repo/flask-image:v1']
    id: 'Push Docker Image 2'

  # Deploy the application
  - name: 'google/cloud-sdk:latest'
    entrypoint: 'sh'
    args:
    - -xe
    - -c
    - |
        gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
        gcloud deploy apply --file deploy/dev.yaml --region=us-central1
        gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml

options:
  logging: CLOUD_LOGGING_ONLY
