apiVersion: skaffold/v4beta9
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./kubernetes/*
deploy:
  kubectl: {}
  logs:
    prefix: container

deploy:
  kubectl:
    manifests:
      paths:
        - k8s/prod/*
    context: gke_my-project_us-central1_my-cluster
