apiVersion: skaffold/v4beta9
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - ./kubernetes/*  # Path to your Kubernetes manifests
deploy:
  kubectl:
    manifests:
      paths:
        - ./kubernetes/*  # Path to your Kubernetes manifests
    context: gke_${t-project-449309}_us-central1_${cluster-1}  # GKE cluster context
  logs:
    prefix: container