apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/t-project-449309/locations/us-central1-c/clusters/cluster-1

