apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cicd-pipeline
  annotations: {}
  labels: {}
description: cicd-pipeline
gke:
  cluster: projects/t-project-449309/locations/us-central1-c/clusters/my-first-cluster-1

