
# DeliveryPipeline
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
    - targetId: cicd-pipeline # Correct referencee
    - targetId: prod
