# deploy/pipeline.yaml
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/t-project-449309/locations/us-central1-c/clusters/cluster-1
---
apiVersion: deploy.cloud.google.com/v1  # Corrected API version
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
    - targetId: dev-target  # Must match the Target name above #k