
# DeliveryPipeline
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: poc-pipeline
  labels:
    app: cicd
description:  poc-pipeline
serialPipeline:
  stages:
    - targetId: poc-dev #Correct referencee
      profiles: []
    - targetId: poc-prod
      profiles: []
