apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/t-project-449309/locations/us-central1/clusters/cluster-1

apiVersion: deploy.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev-target  # Updated to match the name of the Target resource
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  - targetId: prod
  #   profiles:
  #   - prod
