# Target
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: cicd-pipeline-target-1
description: dev
gke:
  cluster: projects/t-project-449309/locations/us-central1/clusters/my-first-cluster-1
---
# DeliveryPipeline
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-pipeline
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
    - targetId: cicd-pipeline-target-1 # Correct reference