apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
requireApproval: true
gke:
  cluster: projects/t-project-449309/locations/us-central1-c/clusters/my-first-cluster-1
executionConfigs:
  - usages: [RENDER, DEPLOY]
    serviceAccount: 482203088783-compute@developer.gserviceaccount.com
 


